[versions]
junit-jupiter = "5.10.0"
guava = "33.3.0-jre"


[libraries]
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }

guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }